export const SET_REPORT_DATA = 'SET_REPORT_DATA';
export const SET_EMAIL_LOGS = 'SET_EMAIL_LOGS';
export const SET_SMS_LOGS = 'SET_SMS_LOGS';
export const SET_STATUS_DATA = 'SET_STATUS_DATA';
export const SET_DRIVER_LOGS = 'SET_DRIVER_LOGS';
export const SET_DELIVERY_LOGS = 'SET_DELIVERY_LOGS';
export const SET_REFRESH = 'SET_REFRESH';